<?php
/**
 * PaymentsApi
 * PHP version 5
 *
 * @category Class
 * @package  Bleumi\Pay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bleumi Pay REST API
 *
 * A simple and powerful REST API to integrate ERC-20, Ethereum, xDai, Algorand payments and/or payouts into your business or application
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@bleumi.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Bleumi\Pay\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Bleumi\Pay\ApiException;
use Bleumi\Pay\Configuration;
use Bleumi\Pay\HeaderSelector;
use Bleumi\Pay\ObjectSerializer;
use Bleumi\Pay\RequestValidator;

/**
 * PaymentsApi Class Doc Comment
 *
 * @category Class
 * @package  Bleumi\Pay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PaymentsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createPayment
     *
     * Generate a unique wallet address in the specified network to accept payment
     *
     * @param  \Bleumi\Pay\Model\CreatePaymentRequest $body body (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Network in which payment is to be created. Please refer documentation for Supported Networks (optional)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Bleumi\Pay\Model\CreatePaymentResponse
     */
    public function createPayment($body, $chain = null)
    {
        list($response) = $this->createPaymentWithHttpInfo($body, $chain);
        return $response;
    }

    /**
     * Operation createPaymentWithHttpInfo
     *
     * Generate a unique wallet address in the specified network to accept payment
     *
     * @param  \Bleumi\Pay\Model\CreatePaymentRequest $body (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Network in which payment is to be created. Please refer documentation for Supported Networks (optional)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Bleumi\Pay\Model\CreatePaymentResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function createPaymentWithHttpInfo($body, $chain = null)
    {
        $returnType = '\Bleumi\Pay\Model\CreatePaymentResponse';
        $request = $this->createPaymentRequest($body, $chain);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\CreatePaymentResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createPaymentAsync
     *
     * Generate a unique wallet address in the specified network to accept payment
     *
     * @param  \Bleumi\Pay\Model\CreatePaymentRequest $body (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Network in which payment is to be created. Please refer documentation for Supported Networks (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createPaymentAsync($body, $chain = null)
    {
        return $this->createPaymentAsyncWithHttpInfo($body, $chain)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createPaymentAsyncWithHttpInfo
     *
     * Generate a unique wallet address in the specified network to accept payment
     *
     * @param  \Bleumi\Pay\Model\CreatePaymentRequest $body (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Network in which payment is to be created. Please refer documentation for Supported Networks (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createPaymentAsyncWithHttpInfo($body, $chain = null)
    {
        $returnType = '\Bleumi\Pay\Model\CreatePaymentResponse';
        $request = $this->createPaymentRequest($body, $chain);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createPayment'
     *
     * @param  \Bleumi\Pay\Model\CreatePaymentRequest $body (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Network in which payment is to be created. Please refer documentation for Supported Networks (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createPaymentRequest($body, $chain = null)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling createPayment'
            );
        }

        $resourcePath = '/v1/payment';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($chain !== null) {
            $queryParams['chain'] = ObjectSerializer::toQueryValue($chain);
        }

        //Bleumi Pay - Customization : Adding validation for request parameters
        $msg = RequestValidator::validateCreatePaymentRequest($body, $chain);
        if ($msg !== null ) {
            throw new \InvalidArgumentException(
                $msg . ' when calling createPayment'
            );
        }
        //Bleumi Pay - Customization : Ends

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPayment
     *
     * Retrieve the wallet addresses & token balances for a given payment
     *
     * @param  string $id Unique identifier of the payment (specified during createPayment) to retrieve (required)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Bleumi\Pay\Model\Payment
     */
    public function getPayment($id)
    {
        list($response) = $this->getPaymentWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation getPaymentWithHttpInfo
     *
     * Retrieve the wallet addresses & token balances for a given payment
     *
     * @param  string $id Unique identifier of the payment (specified during createPayment) to retrieve (required)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Bleumi\Pay\Model\Payment, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPaymentWithHttpInfo($id)
    {
        $returnType = '\Bleumi\Pay\Model\Payment';
        $request = $this->getPaymentRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\Payment',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getPaymentAsync
     *
     * Retrieve the wallet addresses & token balances for a given payment
     *
     * @param  string $id Unique identifier of the payment (specified during createPayment) to retrieve (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaymentAsync($id)
    {
        return $this->getPaymentAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPaymentAsyncWithHttpInfo
     *
     * Retrieve the wallet addresses & token balances for a given payment
     *
     * @param  string $id Unique identifier of the payment (specified during createPayment) to retrieve (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaymentAsyncWithHttpInfo($id)
    {
        $returnType = '\Bleumi\Pay\Model\Payment';
        $request = $this->getPaymentRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPayment'
     *
     * @param  string $id Unique identifier of the payment (specified during createPayment) to retrieve (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getPaymentRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getPayment'
            );
        }

        $resourcePath = '/v1/payment/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getPaymentOperation
     *
     * Retrieve a payment operation for a specific payment.
     *
     * @param  string $id Unique identifier of the payment (specified during [Create a Payment](#createPayment)) (required)
     * @param  string $txid ID of a specific operation of the payment (required)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Bleumi\Pay\Model\PaymentOperation
     */
    public function getPaymentOperation($id, $txid)
    {
        list($response) = $this->getPaymentOperationWithHttpInfo($id, $txid);
        return $response;
    }

    /**
     * Operation getPaymentOperationWithHttpInfo
     *
     * Retrieve a payment operation for a specific payment.
     *
     * @param  string $id Unique identifier of the payment (specified during [Create a Payment](#createPayment)) (required)
     * @param  string $txid ID of a specific operation of the payment (required)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Bleumi\Pay\Model\PaymentOperation, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPaymentOperationWithHttpInfo($id, $txid)
    {
        $returnType = '\Bleumi\Pay\Model\PaymentOperation';
        $request = $this->getPaymentOperationRequest($id, $txid);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\PaymentOperation',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getPaymentOperationAsync
     *
     * Retrieve a payment operation for a specific payment.
     *
     * @param  string $id Unique identifier of the payment (specified during [Create a Payment](#createPayment)) (required)
     * @param  string $txid ID of a specific operation of the payment (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaymentOperationAsync($id, $txid)
    {
        return $this->getPaymentOperationAsyncWithHttpInfo($id, $txid)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPaymentOperationAsyncWithHttpInfo
     *
     * Retrieve a payment operation for a specific payment.
     *
     * @param  string $id Unique identifier of the payment (specified during [Create a Payment](#createPayment)) (required)
     * @param  string $txid ID of a specific operation of the payment (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaymentOperationAsyncWithHttpInfo($id, $txid)
    {
        $returnType = '\Bleumi\Pay\Model\PaymentOperation';
        $request = $this->getPaymentOperationRequest($id, $txid);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPaymentOperation'
     *
     * @param  string $id Unique identifier of the payment (specified during [Create a Payment](#createPayment)) (required)
     * @param  string $txid ID of a specific operation of the payment (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getPaymentOperationRequest($id, $txid)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getPaymentOperation'
            );
        }
        // verify the required parameter 'txid' is set
        if ($txid === null || (is_array($txid) && count($txid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $txid when calling getPaymentOperation'
            );
        }

        $resourcePath = '/v1/payment/{id}/operation/{txid}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }
        // path params
        if ($txid !== null) {
            $resourcePath = str_replace(
                '{' . 'txid' . '}',
                ObjectSerializer::toPathValue($txid),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listPaymentOperations
     *
     * Retrieve all payment operations for a specific payment.
     *
     * @param  string $id Unique identifier of the payment (specified during [Create a Payment](#createPayment)) (required)
     * @param  string $next_token Cursor to start results from (optional)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Bleumi\Pay\Model\PaginatedPaymentOperations
     */
    public function listPaymentOperations($id, $next_token = null)
    {
        list($response) = $this->listPaymentOperationsWithHttpInfo($id, $next_token);
        return $response;
    }

    /**
     * Operation listPaymentOperationsWithHttpInfo
     *
     * Retrieve all payment operations for a specific payment.
     *
     * @param  string $id Unique identifier of the payment (specified during [Create a Payment](#createPayment)) (required)
     * @param  string $next_token Cursor to start results from (optional)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Bleumi\Pay\Model\PaginatedPaymentOperations, HTTP status code, HTTP response headers (array of strings)
     */
    public function listPaymentOperationsWithHttpInfo($id, $next_token = null)
    {
        $returnType = '\Bleumi\Pay\Model\PaginatedPaymentOperations';
        $request = $this->listPaymentOperationsRequest($id, $next_token);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\PaginatedPaymentOperations',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listPaymentOperationsAsync
     *
     * Retrieve all payment operations for a specific payment.
     *
     * @param  string $id Unique identifier of the payment (specified during [Create a Payment](#createPayment)) (required)
     * @param  string $next_token Cursor to start results from (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listPaymentOperationsAsync($id, $next_token = null)
    {
        return $this->listPaymentOperationsAsyncWithHttpInfo($id, $next_token)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listPaymentOperationsAsyncWithHttpInfo
     *
     * Retrieve all payment operations for a specific payment.
     *
     * @param  string $id Unique identifier of the payment (specified during [Create a Payment](#createPayment)) (required)
     * @param  string $next_token Cursor to start results from (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listPaymentOperationsAsyncWithHttpInfo($id, $next_token = null)
    {
        $returnType = '\Bleumi\Pay\Model\PaginatedPaymentOperations';
        $request = $this->listPaymentOperationsRequest($id, $next_token);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listPaymentOperations'
     *
     * @param  string $id Unique identifier of the payment (specified during [Create a Payment](#createPayment)) (required)
     * @param  string $next_token Cursor to start results from (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function listPaymentOperationsRequest($id, $next_token = null)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling listPaymentOperations'
            );
        }

        $resourcePath = '/v1/payment/{id}/operation';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($next_token !== null) {
            $queryParams['nextToken'] = ObjectSerializer::toQueryValue($next_token);
        }

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listPayments
     *
     * Retrieve all payments created.
     *
     * @param  string $next_token Cursor to start results from (optional)
     * @param  string $sort_by Sort payments by (optional)
     * @param  string $sort_order Sort Order (optional)
     * @param  string $start_at Get payments from this timestamp (unix) (optional)
     * @param  string $end_at Get payments till this timestamp (unix) (optional)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Bleumi\Pay\Model\PaginatedPayments
     */
    public function listPayments($next_token = null, $sort_by = null, $sort_order = null, $start_at = null, $end_at = null)
    {
        list($response) = $this->listPaymentsWithHttpInfo($next_token, $sort_by, $sort_order, $start_at, $end_at);
        return $response;
    }

    /**
     * Operation listPaymentsWithHttpInfo
     *
     * Retrieve all payments created.
     *
     * @param  string $next_token Cursor to start results from (optional)
     * @param  string $sort_by Sort payments by (optional)
     * @param  string $sort_order Sort Order (optional)
     * @param  string $start_at Get payments from this timestamp (unix) (optional)
     * @param  string $end_at Get payments till this timestamp (unix) (optional)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Bleumi\Pay\Model\PaginatedPayments, HTTP status code, HTTP response headers (array of strings)
     */
    public function listPaymentsWithHttpInfo($next_token = null, $sort_by = null, $sort_order = null, $start_at = null, $end_at = null)
    {
        $returnType = '\Bleumi\Pay\Model\PaginatedPayments';
        $request = $this->listPaymentsRequest($next_token, $sort_by, $sort_order, $start_at, $end_at);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\PaginatedPayments',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listPaymentsAsync
     *
     * Retrieve all payments created.
     *
     * @param  string $next_token Cursor to start results from (optional)
     * @param  string $sort_by Sort payments by (optional)
     * @param  string $sort_order Sort Order (optional)
     * @param  string $start_at Get payments from this timestamp (unix) (optional)
     * @param  string $end_at Get payments till this timestamp (unix) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listPaymentsAsync($next_token = null, $sort_by = null, $sort_order = null, $start_at = null, $end_at = null)
    {
        return $this->listPaymentsAsyncWithHttpInfo($next_token, $sort_by, $sort_order, $start_at, $end_at)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listPaymentsAsyncWithHttpInfo
     *
     * Retrieve all payments created.
     *
     * @param  string $next_token Cursor to start results from (optional)
     * @param  string $sort_by Sort payments by (optional)
     * @param  string $sort_order Sort Order (optional)
     * @param  string $start_at Get payments from this timestamp (unix) (optional)
     * @param  string $end_at Get payments till this timestamp (unix) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listPaymentsAsyncWithHttpInfo($next_token = null, $sort_by = null, $sort_order = null, $start_at = null, $end_at = null)
    {
        $returnType = '\Bleumi\Pay\Model\PaginatedPayments';
        $request = $this->listPaymentsRequest($next_token, $sort_by, $sort_order, $start_at, $end_at);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listPayments'
     *
     * @param  string $next_token Cursor to start results from (optional)
     * @param  string $sort_by Sort payments by (optional)
     * @param  string $sort_order Sort Order (optional)
     * @param  string $start_at Get payments from this timestamp (unix) (optional)
     * @param  string $end_at Get payments till this timestamp (unix) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function listPaymentsRequest($next_token = null, $sort_by = null, $sort_order = null, $start_at = null, $end_at = null)
    {

        $resourcePath = '/v1/payment';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($next_token !== null) {
            $queryParams['nextToken'] = ObjectSerializer::toQueryValue($next_token);
        }
        // query params
        if ($sort_by !== null) {
            $queryParams['sortBy'] = ObjectSerializer::toQueryValue($sort_by);
        }
        // query params
        if ($sort_order !== null) {
            $queryParams['sortOrder'] = ObjectSerializer::toQueryValue($sort_order);
        }
        // query params
        if ($start_at !== null) {
            $queryParams['startAt'] = ObjectSerializer::toQueryValue($start_at);
        }
        // query params
        if ($end_at !== null) {
            $queryParams['endAt'] = ObjectSerializer::toQueryValue($end_at);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation refundPayment
     *
     * Refund the balance of a token for a given payment to the buyerAddress
     *
     * @param  \Bleumi\Pay\Model\PaymentRefundRequest $body Request body - used to specify the token to refund. (required)
     * @param  string $id Unique identifier of the payment (specified during createPayment) (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Ethereum network in which payment is to be refunded. (optional)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Bleumi\Pay\Model\PaymentOperationResponse
     */
    public function refundPayment($body, $id, $chain = null)
    {
        list($response) = $this->refundPaymentWithHttpInfo($body, $id, $chain);
        return $response;
    }

    /**
     * Operation refundPaymentWithHttpInfo
     *
     * Refund the balance of a token for a given payment to the buyerAddress
     *
     * @param  \Bleumi\Pay\Model\PaymentRefundRequest $body Request body - used to specify the token to refund. (required)
     * @param  string $id Unique identifier of the payment (specified during createPayment) (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Ethereum network in which payment is to be refunded. (optional)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Bleumi\Pay\Model\PaymentOperationResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function refundPaymentWithHttpInfo($body, $id, $chain = null)
    {
        $returnType = '\Bleumi\Pay\Model\PaymentOperationResponse';
        $request = $this->refundPaymentRequest($body, $id, $chain);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\PaymentOperationResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation refundPaymentAsync
     *
     * Refund the balance of a token for a given payment to the buyerAddress
     *
     * @param  \Bleumi\Pay\Model\PaymentRefundRequest $body Request body - used to specify the token to refund. (required)
     * @param  string $id Unique identifier of the payment (specified during createPayment) (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Ethereum network in which payment is to be refunded. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function refundPaymentAsync($body, $id, $chain = null)
    {
        return $this->refundPaymentAsyncWithHttpInfo($body, $id, $chain)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation refundPaymentAsyncWithHttpInfo
     *
     * Refund the balance of a token for a given payment to the buyerAddress
     *
     * @param  \Bleumi\Pay\Model\PaymentRefundRequest $body Request body - used to specify the token to refund. (required)
     * @param  string $id Unique identifier of the payment (specified during createPayment) (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Ethereum network in which payment is to be refunded. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function refundPaymentAsyncWithHttpInfo($body, $id, $chain = null)
    {
        $returnType = '\Bleumi\Pay\Model\PaymentOperationResponse';
        $request = $this->refundPaymentRequest($body, $id, $chain);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'refundPayment'
     *
     * @param  \Bleumi\Pay\Model\PaymentRefundRequest $body Request body - used to specify the token to refund. (required)
     * @param  string $id Unique identifier of the payment (specified during createPayment) (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Ethereum network in which payment is to be refunded. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function refundPaymentRequest($body, $id, $chain = null)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling refundPayment'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling refundPayment'
            );
        }

        $resourcePath = '/v1/payment/{id}/refund';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($chain !== null) {
            $queryParams['chain'] = ObjectSerializer::toQueryValue($chain);
        }

        //Bleumi Pay - Customization : Adding validation for request parameters
        $msg = RequestValidator::validateRefundPaymentRequest($body, $chain);
        if ($msg !== null ) {
            throw new \InvalidArgumentException(
                $msg . ' when calling refundPayment'
            );
        }
        //Bleumi Pay - Customization : Ends

        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation settlePayment
     *
     * Settle a specific amount of a token for a given payment to the transferAddress and remaining balance (if any) will be refunded to the buyerAddress
     *
     * @param  \Bleumi\Pay\Model\PaymentSettleRequest $body Request body - used to specify the amount to settle. (required)
     * @param  string $id Unique identifier of the payment (specified during createPayment) (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Ethereum network in which payment is to be settled. (optional)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Bleumi\Pay\Model\PaymentOperationResponse
     */
    public function settlePayment($body, $id, $chain = null)
    {
        list($response) = $this->settlePaymentWithHttpInfo($body, $id, $chain);
        return $response;
    }

    /**
     * Operation settlePaymentWithHttpInfo
     *
     * Settle a specific amount of a token for a given payment to the transferAddress and remaining balance (if any) will be refunded to the buyerAddress
     *
     * @param  \Bleumi\Pay\Model\PaymentSettleRequest $body Request body - used to specify the amount to settle. (required)
     * @param  string $id Unique identifier of the payment (specified during createPayment) (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Ethereum network in which payment is to be settled. (optional)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Bleumi\Pay\Model\PaymentOperationResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function settlePaymentWithHttpInfo($body, $id, $chain = null)
    {
        $returnType = '\Bleumi\Pay\Model\PaymentOperationResponse';
        $request = $this->settlePaymentRequest($body, $id, $chain);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\PaymentOperationResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation settlePaymentAsync
     *
     * Settle a specific amount of a token for a given payment to the transferAddress and remaining balance (if any) will be refunded to the buyerAddress
     *
     * @param  \Bleumi\Pay\Model\PaymentSettleRequest $body Request body - used to specify the amount to settle. (required)
     * @param  string $id Unique identifier of the payment (specified during createPayment) (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Ethereum network in which payment is to be settled. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function settlePaymentAsync($body, $id, $chain = null)
    {
        return $this->settlePaymentAsyncWithHttpInfo($body, $id, $chain)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation settlePaymentAsyncWithHttpInfo
     *
     * Settle a specific amount of a token for a given payment to the transferAddress and remaining balance (if any) will be refunded to the buyerAddress
     *
     * @param  \Bleumi\Pay\Model\PaymentSettleRequest $body Request body - used to specify the amount to settle. (required)
     * @param  string $id Unique identifier of the payment (specified during createPayment) (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Ethereum network in which payment is to be settled. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function settlePaymentAsyncWithHttpInfo($body, $id, $chain = null)
    {
        $returnType = '\Bleumi\Pay\Model\PaymentOperationResponse';
        $request = $this->settlePaymentRequest($body, $id, $chain);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'settlePayment'
     *
     * @param  \Bleumi\Pay\Model\PaymentSettleRequest $body Request body - used to specify the amount to settle. (required)
     * @param  string $id Unique identifier of the payment (specified during createPayment) (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Ethereum network in which payment is to be settled. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function settlePaymentRequest($body, $id, $chain = null)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling settlePayment'
            );
        }
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling settlePayment'
            );
        }

        $resourcePath = '/v1/payment/{id}/settle';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($chain !== null) {
            $queryParams['chain'] = ObjectSerializer::toQueryValue($chain);
        }

        //Bleumi Pay - Customization : Adding validation for request parameters
        $msg = RequestValidator::validateSettlePaymentRequest($body, $chain);
        if ($msg !== null ) {
            throw new \InvalidArgumentException(
                $msg . ' when calling settlePayment'
            );
        }
        //Bleumi Pay - Customization : Ends
        
        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
