<?php
/**
 * PayoutsApi
 * PHP version 5
 *
 * @category Class
 * @package  Bleumi\Pay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bleumi Pay REST API
 *
 * A simple and powerful REST API to integrate ERC-20, Ethereum, xDai, Algorand payments and/or payouts into your business or application
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@bleumi.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Bleumi\Pay\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Bleumi\Pay\ApiException;
use Bleumi\Pay\Configuration;
use Bleumi\Pay\HeaderSelector;
use Bleumi\Pay\ObjectSerializer;
use Bleumi\Pay\RequestValidator;

/**
 * PayoutsApi Class Doc Comment
 *
 * @category Class
 * @package  Bleumi\Pay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PayoutsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createPayout
     *
     * Create a payout.
     *
     * @param  \Bleumi\Pay\Model\CreatePayoutRequest $body Request body - used to specify payout creation parameters. (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Ethereum network in which payment is to be created. Please refer documentation for Supported Networks (optional)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Bleumi\Pay\Model\CreatePayoutResponse
     */
    public function createPayout($body, $chain = null)
    {
        list($response) = $this->createPayoutWithHttpInfo($body, $chain);
        return $response;
    }

    /**
     * Operation createPayoutWithHttpInfo
     *
     * Create a payout.
     *
     * @param  \Bleumi\Pay\Model\CreatePayoutRequest $body Request body - used to specify payout creation parameters. (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Ethereum network in which payment is to be created. Please refer documentation for Supported Networks (optional)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Bleumi\Pay\Model\CreatePayoutResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function createPayoutWithHttpInfo($body, $chain = null)
    {
        $returnType = '\Bleumi\Pay\Model\CreatePayoutResponse';
        $request = $this->createPayoutRequest($body, $chain);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\CreatePayoutResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createPayoutAsync
     *
     * Create a payout.
     *
     * @param  \Bleumi\Pay\Model\CreatePayoutRequest $body Request body - used to specify payout creation parameters. (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Ethereum network in which payment is to be created. Please refer documentation for Supported Networks (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createPayoutAsync($body, $chain = null)
    {
        return $this->createPayoutAsyncWithHttpInfo($body, $chain)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createPayoutAsyncWithHttpInfo
     *
     * Create a payout.
     *
     * @param  \Bleumi\Pay\Model\CreatePayoutRequest $body Request body - used to specify payout creation parameters. (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Ethereum network in which payment is to be created. Please refer documentation for Supported Networks (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createPayoutAsyncWithHttpInfo($body, $chain = null)
    {
        $returnType = '\Bleumi\Pay\Model\CreatePayoutResponse';
        $request = $this->createPayoutRequest($body, $chain);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createPayout'
     *
     * @param  \Bleumi\Pay\Model\CreatePayoutRequest $body Request body - used to specify payout creation parameters. (required)
     * @param  \Bleumi\Pay\Model\Chain $chain Ethereum network in which payment is to be created. Please refer documentation for Supported Networks (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function createPayoutRequest($body, $chain = null)
    {
        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling createPayout'
            );
        }

        //Bleumi Pay - Customization : Adding validation for request parameters
        $msg = RequestValidator::validateCreatePayoutRequest($body, $chain);
        if ($msg !== null ) {
            throw new \InvalidArgumentException(
                $msg . ' when calling createPayout'
            );
        }
        //Bleumi Pay - Customization : Ends

        $resourcePath = '/v1/payout';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($chain !== null) {
            $queryParams['chain'] = ObjectSerializer::toQueryValue($chain);
        }


        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listPayouts
     *
     * Returns a list of payouts
     *
     * @param  string $next_token Cursor to start results from (optional)
     * @param  string $sort_by Sort payments by (optional)
     * @param  string $start_at Get payouts from this timestamp (unix) (optional)
     * @param  string $end_at Get payouts till this timestamp (unix) (optional)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Bleumi\Pay\Model\PaginatedPayoutItems
     */
    public function listPayouts($next_token = null, $sort_by = null, $start_at = null, $end_at = null)
    {
        list($response) = $this->listPayoutsWithHttpInfo($next_token, $sort_by, $start_at, $end_at);
        return $response;
    }

    /**
     * Operation listPayoutsWithHttpInfo
     *
     * Returns a list of payouts
     *
     * @param  string $next_token Cursor to start results from (optional)
     * @param  string $sort_by Sort payments by (optional)
     * @param  string $start_at Get payouts from this timestamp (unix) (optional)
     * @param  string $end_at Get payouts till this timestamp (unix) (optional)
     *
     * @throws \Bleumi\Pay\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Bleumi\Pay\Model\PaginatedPayoutItems, HTTP status code, HTTP response headers (array of strings)
     */
    public function listPayoutsWithHttpInfo($next_token = null, $sort_by = null, $start_at = null, $end_at = null)
    {
        $returnType = '\Bleumi\Pay\Model\PaginatedPayoutItems';
        $request = $this->listPayoutsRequest($next_token, $sort_by, $start_at, $end_at);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\PaginatedPayoutItems',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Bleumi\Pay\Model\BadRequest',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation listPayoutsAsync
     *
     * Returns a list of payouts
     *
     * @param  string $next_token Cursor to start results from (optional)
     * @param  string $sort_by Sort payments by (optional)
     * @param  string $start_at Get payouts from this timestamp (unix) (optional)
     * @param  string $end_at Get payouts till this timestamp (unix) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listPayoutsAsync($next_token = null, $sort_by = null, $start_at = null, $end_at = null)
    {
        return $this->listPayoutsAsyncWithHttpInfo($next_token, $sort_by, $start_at, $end_at)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listPayoutsAsyncWithHttpInfo
     *
     * Returns a list of payouts
     *
     * @param  string $next_token Cursor to start results from (optional)
     * @param  string $sort_by Sort payments by (optional)
     * @param  string $start_at Get payouts from this timestamp (unix) (optional)
     * @param  string $end_at Get payouts till this timestamp (unix) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listPayoutsAsyncWithHttpInfo($next_token = null, $sort_by = null, $start_at = null, $end_at = null)
    {
        $returnType = '\Bleumi\Pay\Model\PaginatedPayoutItems';
        $request = $this->listPayoutsRequest($next_token, $sort_by, $start_at, $end_at);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listPayouts'
     *
     * @param  string $next_token Cursor to start results from (optional)
     * @param  string $sort_by Sort payments by (optional)
     * @param  string $start_at Get payouts from this timestamp (unix) (optional)
     * @param  string $end_at Get payouts till this timestamp (unix) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function listPayoutsRequest($next_token = null, $sort_by = null, $start_at = null, $end_at = null)
    {

        $resourcePath = '/v1/payout';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($next_token !== null) {
            $queryParams['nextToken'] = ObjectSerializer::toQueryValue($next_token);
        }
        // query params
        if ($sort_by !== null) {
            $queryParams['sortBy'] = ObjectSerializer::toQueryValue($sort_by);
        }
        // query params
        if ($start_at !== null) {
            $queryParams['startAt'] = ObjectSerializer::toQueryValue($start_at);
        }
        // query params
        if ($end_at !== null) {
            $queryParams['endAt'] = ObjectSerializer::toQueryValue($end_at);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
