<?php
/**
 * Chain
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bleumi\Pay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bleumi Pay REST API
 *
 * A simple and powerful REST API to integrate ERC-20, Ethereum, xDai, Algorand payments and/or payouts into your business or application
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@bleumi.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Bleumi\Pay\Model;
use \Bleumi\Pay\ObjectSerializer;

/**
 * Chain Class Doc Comment
 *
 * @category Class
 * @description Network enumeration. Please refer to the Supported Networks.
 * @package  Bleumi\Pay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Chain
{
    /**
     * Possible values of this enum
     */
    const MAINNET = 'mainnet';
const GOERLI = 'goerli';
const XDAI = 'xdai';
const XDAI_TESTNET = 'xdai_testnet';
const ALG_MAINNET = 'alg_mainnet';
const ALG_TESTNET = 'alg_testnet';
const RSK = 'rsk';
const RSK_TESTNET = 'rsk_testnet';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MAINNET,
self::GOERLI,
self::XDAI,
self::XDAI_TESTNET,
self::ALG_MAINNET,
self::ALG_TESTNET,
self::RSK,
self::RSK_TESTNET,        ];
    }
}
