<?php
/**
 * Chain
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bleumi\Pay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bleumi Pay API
 *
 * A simple and powerful REST API to integrate ERC-20, Ethereum, xDai payments and/or payouts into your business or application
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@bleumi.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Bleumi\Pay\Model;
use \Bleumi\Pay\ObjectSerializer;

/**
 * Chain Class Doc Comment
 *
 * @category Class
 * @package  Bleumi\Pay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Chain
{
    /**
     * Possible values of this enum
     */
    const MAINNET = 'mainnet';
const ROPSTEN = 'ropsten';
const GOERLI = 'goerli';
const KOVAN = 'kovan';
const RINKEBY = 'rinkeby';
const XDAI = 'xdai';
const XDAI_TESTNET = 'xdai_testnet';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MAINNET,
self::ROPSTEN,
self::GOERLI,
self::KOVAN,
self::RINKEBY,
self::XDAI,
self::XDAI_TESTNET,        ];
    }
}
