<?php
/**
 * PaymentStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Bleumi\Pay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bleumi Pay API
 *
 * The power of fiat at the speed of cryptocurrency
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9-SNAPSHOT
 */


namespace Bleumi\Pay\Model;
use \Bleumi\Pay\ObjectSerializer;

/**
 * PaymentStatus Class Doc Comment
 *
 * @category Class
 * @package  Bleumi\Pay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PaymentStatus
{
    /**
     * Possible values of this enum
     */
    const OUTSTANDING = 'outstanding';
const PAID = 'paid';
const PARTIALLY_PAID = 'partiallyPaid';
const CANCELLED = 'cancelled';
const SETTLED = 'settled';
const FAILED = 'failed';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OUTSTANDING,
self::PAID,
self::PARTIALLY_PAID,
self::CANCELLED,
self::SETTLED,
self::FAILED,        ];
    }
}
